apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-read-only
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - proxy
      - redirect
      - watch
    apiGroups:
      - '*'
    resources:
      - alertmanagers
      - apiservices
      - apiservices/status
      - appversions
      - authcodes
      - authrequests
      - bindings
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
      - channeloperatorconfigs
      - componentstatuses
      - configmaps
      - connectors
      - controllerrevisions
      - customresourcedefinitions
      - customresourcedefinitions/status
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/rollback
      - deployments/scale
      - deployments/status
      - endpoints
      - etcdclusters
      - events
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
      - ingresses
      - ingresses/status
      - jobs
      - jobs/status
      - limitranges
      - localsubjectaccessreviews
      - migrationstatuses
      - namespaces
      - namespaces/finalize
      - namespaces/status
      - networkpolicies
      - oauth2clients
      - offlinesessionses
      - passwords
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - persistentvolumes
      - persistentvolumes/status
      - poddisruptionbudgets
      - poddisruptionbudgets/status
      - podpresets
      - pods
      - pods/attach
      - pods/binding
      - pods/eviction
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
      - pods/status
      - podsecuritypolicies
      - podtemplates
      - prometheuses
      - refreshtokens
      - replicasets
      - replicasets/scale
      - replicasets/status
      - replicationcontrollers
      - replicationcontrollers/scale
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      - selfsubjectaccessreviews
      - serviceaccounts
      - servicemonitors
      - services
      - services/proxy
      - services/status
      - signingkeies
      - statefulsets
      - statefulsets/status
      - storageclasses
      - subjectaccessreviews
      - tectonicversions
      - tokenreviews
