apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: default
  labels:
    k8s-app: kube-state-metrics
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      port: http-metrics
      targetPort: 0
  jobLabel: simple-app
  namespaceSelector:
    matchNames:
      - tectonic-system
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
